name: Coverage

on: pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: Install dependencies
        run: npm ci
      - name: Jest test with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
