name: ESLint

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
